### ISSUE TITLE
Uncaught TypeError: bind is not a function

### ISSUE THREAD

**Issue by zhaohaodang** [kazupon/vue-i18n#117]
### package
vue-i18n 5.0.2
npm 4.2.0 
vue  2.2.0
### location
`set: bind(function (val) { langVM.lang = val; }, langVM)` in vue-i18n.common.js?9608:196 
how to solve this problem?

**Comment by sourcecodingltd** [comment]
`vue-i18n.common.js` - `var bind = Vue.util.bind;`

From vue changelog - 

https://github.com/vuejs/vue/releases

Many exposed methods and properties on Vue.util have been removed. If you previously relied on them, you should migrate off of them since this object is intended for internal use only - it is not (and has never been) considered part of the public API and may change without notice in the future.

**Comment by zhaohaodang** [comment]
thx!! I reinstall vue2.1.0 and solve the issue

**Comment by kazupon** [comment]
Thank you always your using!
To upgrade v5.0.3, You can resolve the issue.  :)

**Comment by devloe** [comment]
What version of vue-i18n do I have to use to get it working on Vue 2.1.8?
